//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexandria.Engines.DarkSouls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alexandria.Engines.DarkSouls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This engine provides functionality for From Software&apos;s engine used for Demon Souls, Dark Souls, and Dark Souls 2..
        /// </summary>
        internal static string EngineDescription {
            get {
                return ResourceManager.GetString("EngineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demon Souls/Dark Souls/Dark Souls 2 Engine.
        /// </summary>
        internal static string EngineName {
            get {
                return ResourceManager.GetString("EngineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; 2435/2435 (100%)
        ////chr/c0000.anibnd.dcx
        ////chr/c0000.chrbnd.dcx
        ////chr/c0000.esd.dcx
        ////chr/c0000_a00_hi.anibnd.dcx
        ////chr/c0000_a00_lo.anibnd.dcx
        ////chr/c0000_a00_md.anibnd.dcx
        ////chr/c0000_a0x.anibnd.dcx
        ////chr/c0000_a1x.anibnd.dcx
        ////chr/c0000_a2x.anibnd.dcx
        ////chr/c0000_a3x.anibnd.dcx
        ////chr/c0000_a4x.anibnd.dcx
        ////chr/c0000_a5x.anibnd.dcx
        ////chr/c0000_a6x.anibnd.dcx
        ////chr/c0000_a7x.anibnd.dcx
        ////chr/c0000_a8x.anibnd.dcx
        ////chr/c0000_a9x.anibnd.dcx
        ////chr/c0000_c2060.anibnd.dcx
        ////chr/c0000_c2290.anibnd.dcx
        ////chr/c00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileList1 {
            get {
                return ResourceManager.GetString("FileList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; 3679/3679 (100%)
        ////facegen/FaceGen.fgbnd
        ////font/DbgFont14h.ccm.dcx
        ////font/DbgFont14h.tpf.dcx
        ////font/english/DSFont24.ccm.dcx
        ////font/english/DSFont24.tpf.dcx
        ////font/english/TalkFont24.ccm.dcx
        ////font/english/TalkFont24.tpf.dcx
        ////font/japanese/DSFont24.ccm.dcx
        ////font/japanese/DSFont24.tpf.dcx
        ////font/japanese/TalkFont24.ccm.dcx
        ////font/japanese/TalkFont24.tpf.dcx
        ////font/korean/DSFont24.ccm.dcx
        ////font/korean/DSFont24.tpf.dcx
        ////font/korean/TalkFont24.ccm.dcx
        ////font/korean/TalkFont24.tpf.dcx
        ////font/polish/DSFont2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileList2 {
            get {
                return ResourceManager.GetString("FileList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0	[ System ] dummy bullets
        ///4	[ System ] invalid attack [Common ]
        ///5	Dummy attacks continue out the bullet
        ///10	Template LV1 small damage
        ///11	Template LV2 Medium Damage
        ///12	Template LV3 large damage
        ///13	Futtobi LV4 template ( large )
        ///14	LV5 press template
        ///15	Template LV6 damage slams
        ///16	Futtobi LV7 template ( small)
        ///17	Template LV8 minimal damage
        ///18	Template LV9 damage up wins
        ///19	Futtobi LV10 template ( extra large )
        ///20	Template LV11 breath
        ///21	Template guard
        ///22	Parry template for guard
        ///23	Throw tem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Names_AtkParam_Npc {
            get {
                return ResourceManager.GetString("Names_AtkParam_Npc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A plugin for Demon Souls, Dark Souls, and Dark Souls 2..
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Souls plugin.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
    }
}
