//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexandria.Engines.DarkSouls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alexandria.Engines.DarkSouls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive format (.bhd, .bdt, and many others).
        /// </summary>
        internal static string ArchiveFormatName {
            get {
                return ResourceManager.GetString("ArchiveFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect format (.ffx).
        /// </summary>
        internal static string EffectFormatName {
            get {
                return ResourceManager.GetString("EffectFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emeld format (.emeld).
        /// </summary>
        internal static string EmeldFormatName {
            get {
                return ResourceManager.GetString("EmeldFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This engine provides functionality for From Software&apos;s engine used for Demon Souls, Dark Souls, and Dark Souls 2..
        /// </summary>
        internal static string EngineDescription {
            get {
                return ResourceManager.GetString("EngineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demon Souls/Dark Souls/Dark Souls 2 Engine.
        /// </summary>
        internal static string EngineName {
            get {
                return ResourceManager.GetString("EngineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; 2435/2435 (100%)
        ////chr/c0000.anibnd.dcx
        ////chr/c0000.chrbnd.dcx
        ////chr/c0000.esd.dcx
        ////chr/c0000_a00_hi.anibnd.dcx
        ////chr/c0000_a00_lo.anibnd.dcx
        ////chr/c0000_a00_md.anibnd.dcx
        ////chr/c0000_a0x.anibnd.dcx
        ////chr/c0000_a1x.anibnd.dcx
        ////chr/c0000_a2x.anibnd.dcx
        ////chr/c0000_a3x.anibnd.dcx
        ////chr/c0000_a4x.anibnd.dcx
        ////chr/c0000_a5x.anibnd.dcx
        ////chr/c0000_a6x.anibnd.dcx
        ////chr/c0000_a7x.anibnd.dcx
        ////chr/c0000_a8x.anibnd.dcx
        ////chr/c0000_a9x.anibnd.dcx
        ////chr/c0000_c2060.anibnd.dcx
        ////chr/c0000_c2290.anibnd.dcx
        ////chr/c00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileList1 {
            get {
                return ResourceManager.GetString("FileList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; 3679/3679 (100%)
        ////facegen/FaceGen.fgbnd
        ////font/DbgFont14h.ccm.dcx
        ////font/DbgFont14h.tpf.dcx
        ////font/english/DSFont24.ccm.dcx
        ////font/english/DSFont24.tpf.dcx
        ////font/english/TalkFont24.ccm.dcx
        ////font/english/TalkFont24.tpf.dcx
        ////font/japanese/DSFont24.ccm.dcx
        ////font/japanese/DSFont24.tpf.dcx
        ////font/japanese/TalkFont24.ccm.dcx
        ////font/japanese/TalkFont24.tpf.dcx
        ////font/korean/DSFont24.ccm.dcx
        ////font/korean/DSFont24.tpf.dcx
        ////font/korean/TalkFont24.ccm.dcx
        ////font/korean/TalkFont24.tpf.dcx
        ////font/polish/DSFont2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileList2 {
            get {
                return ResourceManager.GetString("FileList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSSL format (.fssl).
        /// </summary>
        internal static string FsslFormatName {
            get {
                return ResourceManager.GetString("FsslFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCG format (.mcg).
        /// </summary>
        internal static string MCGFormatName {
            get {
                return ResourceManager.GetString("MCGFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP format (.mcp).
        /// </summary>
        internal static string MCPFormatName {
            get {
                return ResourceManager.GetString("MCPFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model format (.flver).
        /// </summary>
        internal static string ModelFormatName {
            get {
                return ResourceManager.GetString("ModelFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter definition format (.paramdef).
        /// </summary>
        internal static string ParameterDefinitionFormatName {
            get {
                return ResourceManager.GetString("ParameterDefinitionFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter table format (.param).
        /// </summary>
        internal static string ParameterTableFormatName {
            get {
                return ResourceManager.GetString("ParameterTableFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A plugin for Demon Souls, Dark Souls, and Dark Souls 2..
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Souls plugin.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String archive format.
        /// </summary>
        internal static string StringArchiveFormatName {
            get {
                return ResourceManager.GetString("StringArchiveFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table archive format.
        /// </summary>
        internal static string TableArchiveFormatName {
            get {
                return ResourceManager.GetString("TableArchiveFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture archive format (.tpf).
        /// </summary>
        internal static string TextureArchiveFormatName {
            get {
                return ResourceManager.GetString("TextureArchiveFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Translations {
            get {
                object obj = ResourceManager.GetObject("Translations", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
