//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexandria.Engines.UltimaUnderworld.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alexandria.Engines.UltimaUnderworld.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The engine for Ultima Underworld, Ultima Underworld 2: The Stygian Abyss, and System Shock..
        /// </summary>
        internal static string EngineDescription {
            get {
                return ResourceManager.GetString("EngineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultima Underworld Engine.
        /// </summary>
        internal static string EngineName {
            get {
                return ResourceManager.GetString("EngineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Shock.
        /// </summary>
        internal static string GameSystemShockName {
            get {
                return ResourceManager.GetString("GameSystemShockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultima Underworld 2.
        /// </summary>
        internal static string GameUltimaUnderworld2Name {
            get {
                return ResourceManager.GetString("GameUltimaUnderworld2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultima Underworld.
        /// </summary>
        internal static string GameUltimaUnderworldName {
            get {
                return ResourceManager.GetString("GameUltimaUnderworldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic archive format (.gr).
        /// </summary>
        internal static string GraphicArchiveFormatName {
            get {
                return ResourceManager.GetString("GraphicArchiveFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette archive format (.dat).
        /// </summary>
        internal static string PaletteArchiveFormatName {
            get {
                return ResourceManager.GetString("PaletteArchiveFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin provides functionality for dealing with Ultima Underworld, Ultima Underworld 2: The Stygian Abyss, and System Shock..
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultima Underworld, Ultima Underworld 2, System Shock.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String package format (.pak).
        /// </summary>
        internal static string StringPackageFormatName {
            get {
                return ResourceManager.GetString("StringPackageFormatName", resourceCulture);
            }
        }
    }
}
