//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moki.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moki.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;abstract&apos; keyword.
        /// </summary>
        internal static string TokenCode_Abstract_Name {
            get {
                return ResourceManager.GetString("TokenCode_Abstract_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;as&apos; keyword.
        /// </summary>
        internal static string TokenCode_As_Name {
            get {
                return ResourceManager.GetString("TokenCode_As_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment &apos;=&apos;.
        /// </summary>
        internal static string TokenCode_Assign_Name {
            get {
                return ResourceManager.GetString("TokenCode_Assign_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and assign &apos;+=&apos;.
        /// </summary>
        internal static string TokenCode_AssignAdd_Name {
            get {
                return ResourceManager.GetString("TokenCode_AssignAdd_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise AND and assign &apos;&amp;=&apos;.
        /// </summary>
        internal static string TokenCode_AssignBitwiseAnd_Name {
            get {
                return ResourceManager.GetString("TokenCode_AssignBitwiseAnd_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise exclusive OR and assign &apos;^=&apos;.
        /// </summary>
        internal static string TokenCode_AssignBitwiseExclusiveOr_Name {
            get {
                return ResourceManager.GetString("TokenCode_AssignBitwiseExclusiveOr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise OR and assign &apos;|=&apos;.
        /// </summary>
        internal static string TokenCode_AssignBitwiseOr_Name {
            get {
                return ResourceManager.GetString("TokenCode_AssignBitwiseOr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide and assign &apos;/=&apos;.
        /// </summary>
        internal static string TokenCode_AssignDivide_Name {
            get {
                return ResourceManager.GetString("TokenCode_AssignDivide_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo and assign &apos;%=&apos;.
        /// </summary>
        internal static string TokenCode_AssignModulus_Name {
            get {
                return ResourceManager.GetString("TokenCode_AssignModulus_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply and assign &apos;*=&apos;.
        /// </summary>
        internal static string TokenCode_AssignMultiply_Name {
            get {
                return ResourceManager.GetString("TokenCode_AssignMultiply_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift left and assign &apos;&lt;&lt;=&apos;.
        /// </summary>
        internal static string TokenCode_AssignShiftLeft_Name {
            get {
                return ResourceManager.GetString("TokenCode_AssignShiftLeft_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift right and assign &apos;&gt;&gt;=&apos;.
        /// </summary>
        internal static string TokenCode_AssignShiftRight_Name {
            get {
                return ResourceManager.GetString("TokenCode_AssignShiftRight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract and assign &apos;-=&apos;.
        /// </summary>
        internal static string TokenCode_AssignSubtract_Name {
            get {
                return ResourceManager.GetString("TokenCode_AssignSubtract_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;base&apos; keyword.
        /// </summary>
        internal static string TokenCode_Base_Name {
            get {
                return ResourceManager.GetString("TokenCode_Base_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise AND &apos;&amp;&apos;.
        /// </summary>
        internal static string TokenCode_BitwiseAnd_Name {
            get {
                return ResourceManager.GetString("TokenCode_BitwiseAnd_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise exclusive OR &apos;^&apos;.
        /// </summary>
        internal static string TokenCode_BitwiseExclusiveOr_Name {
            get {
                return ResourceManager.GetString("TokenCode_BitwiseExclusiveOr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise NOT &apos;~&apos;.
        /// </summary>
        internal static string TokenCode_BitwiseNot_Name {
            get {
                return ResourceManager.GetString("TokenCode_BitwiseNot_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise OR &apos;|&apos;.
        /// </summary>
        internal static string TokenCode_BitwiseOr_Name {
            get {
                return ResourceManager.GetString("TokenCode_BitwiseOr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close square bracket &apos;]&apos;.
        /// </summary>
        internal static string TokenCode_BracketClose_Name {
            get {
                return ResourceManager.GetString("TokenCode_BracketClose_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open square bracket &apos;[&apos;.
        /// </summary>
        internal static string TokenCode_BracketOpen_Name {
            get {
                return ResourceManager.GetString("TokenCode_BracketOpen_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;break&apos; keyword.
        /// </summary>
        internal static string TokenCode_Break_Name {
            get {
                return ResourceManager.GetString("TokenCode_Break_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;case&apos; keyword.
        /// </summary>
        internal static string TokenCode_Case_Name {
            get {
                return ResourceManager.GetString("TokenCode_Case_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;catch&apos; keyword.
        /// </summary>
        internal static string TokenCode_Catch_Name {
            get {
                return ResourceManager.GetString("TokenCode_Catch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;checked&apos; keyword.
        /// </summary>
        internal static string TokenCode_Checked_Name {
            get {
                return ResourceManager.GetString("TokenCode_Checked_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;class&apos; keyword.
        /// </summary>
        internal static string TokenCode_Class_Name {
            get {
                return ResourceManager.GetString("TokenCode_Class_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closure &apos;=&gt;&apos;.
        /// </summary>
        internal static string TokenCode_Closure_Name {
            get {
                return ResourceManager.GetString("TokenCode_Closure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon &apos;:&apos;.
        /// </summary>
        internal static string TokenCode_Colon_Name {
            get {
                return ResourceManager.GetString("TokenCode_Colon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma &apos;,&apos;.
        /// </summary>
        internal static string TokenCode_Comma_Name {
            get {
                return ResourceManager.GetString("TokenCode_Comma_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare equal &apos;==&apos;.
        /// </summary>
        internal static string TokenCode_CompareEqual_Name {
            get {
                return ResourceManager.GetString("TokenCode_CompareEqual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare greater &apos;&gt;&apos;.
        /// </summary>
        internal static string TokenCode_CompareGreater_Name {
            get {
                return ResourceManager.GetString("TokenCode_CompareGreater_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare greater or equal to &apos;&gt;=&apos;.
        /// </summary>
        internal static string TokenCode_CompareGreaterOrEqual_Name {
            get {
                return ResourceManager.GetString("TokenCode_CompareGreaterOrEqual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare less &apos;&lt;&apos;.
        /// </summary>
        internal static string TokenCode_CompareLess_Name {
            get {
                return ResourceManager.GetString("TokenCode_CompareLess_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare less or equal &apos;&lt;=&apos;.
        /// </summary>
        internal static string TokenCode_CompareLessOrEqual_Name {
            get {
                return ResourceManager.GetString("TokenCode_CompareLessOrEqual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare not equal &apos;!=&apos;.
        /// </summary>
        internal static string TokenCode_CompareNotEqual_Name {
            get {
                return ResourceManager.GetString("TokenCode_CompareNotEqual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;const&apos; keyword.
        /// </summary>
        internal static string TokenCode_Const_Name {
            get {
                return ResourceManager.GetString("TokenCode_Const_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;continue&apos; keyword.
        /// </summary>
        internal static string TokenCode_Continue_Name {
            get {
                return ResourceManager.GetString("TokenCode_Continue_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curly close brackets &apos;}&apos;.
        /// </summary>
        internal static string TokenCode_CurlyClose_Name {
            get {
                return ResourceManager.GetString("TokenCode_CurlyClose_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curly open brackets &apos;{&apos;.
        /// </summary>
        internal static string TokenCode_CurlyOpen_Name {
            get {
                return ResourceManager.GetString("TokenCode_CurlyOpen_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrement &apos;--&apos;.
        /// </summary>
        internal static string TokenCode_Decrement_Name {
            get {
                return ResourceManager.GetString("TokenCode_Decrement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;default&apos; keyword.
        /// </summary>
        internal static string TokenCode_Default_Name {
            get {
                return ResourceManager.GetString("TokenCode_Default_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;delegate&apos; keyword.
        /// </summary>
        internal static string TokenCode_Delegate_Name {
            get {
                return ResourceManager.GetString("TokenCode_Delegate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide &apos;/&apos;.
        /// </summary>
        internal static string TokenCode_Divide_Name {
            get {
                return ResourceManager.GetString("TokenCode_Divide_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;do&apos; keyword.
        /// </summary>
        internal static string TokenCode_Do_Name {
            get {
                return ResourceManager.GetString("TokenCode_Do_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot &apos;.&apos;.
        /// </summary>
        internal static string TokenCode_Dot_Name {
            get {
                return ResourceManager.GetString("TokenCode_Dot_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double colon &apos;::&apos;.
        /// </summary>
        internal static string TokenCode_DoubleColon_Name {
            get {
                return ResourceManager.GetString("TokenCode_DoubleColon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;else&apos; keyword.
        /// </summary>
        internal static string TokenCode_Else_Name {
            get {
                return ResourceManager.GetString("TokenCode_Else_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of source.
        /// </summary>
        internal static string TokenCode_EndOfSource_Name {
            get {
                return ResourceManager.GetString("TokenCode_EndOfSource_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;enum&apos; keyword.
        /// </summary>
        internal static string TokenCode_Enum_Name {
            get {
                return ResourceManager.GetString("TokenCode_Enum_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;event&apos; keyword.
        /// </summary>
        internal static string TokenCode_Event_Name {
            get {
                return ResourceManager.GetString("TokenCode_Event_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;explicit&apos; keyword.
        /// </summary>
        internal static string TokenCode_Explicit_Name {
            get {
                return ResourceManager.GetString("TokenCode_Explicit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;extern&apos; keyword.
        /// </summary>
        internal static string TokenCode_Extern_Name {
            get {
                return ResourceManager.GetString("TokenCode_Extern_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;finally&apos; keyword.
        /// </summary>
        internal static string TokenCode_Finally_Name {
            get {
                return ResourceManager.GetString("TokenCode_Finally_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;fixed&apos; keyword.
        /// </summary>
        internal static string TokenCode_Fixed_Name {
            get {
                return ResourceManager.GetString("TokenCode_Fixed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;for&apos; keyword.
        /// </summary>
        internal static string TokenCode_For_Name {
            get {
                return ResourceManager.GetString("TokenCode_For_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;foreach&apos; keyword.
        /// </summary>
        internal static string TokenCode_Foreach_Name {
            get {
                return ResourceManager.GetString("TokenCode_Foreach_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;goto&apos; keyword.
        /// </summary>
        internal static string TokenCode_Goto_Name {
            get {
                return ResourceManager.GetString("TokenCode_Goto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos;.
        /// </summary>
        internal static string TokenCode_Identifier_Name {
            get {
                return ResourceManager.GetString("TokenCode_Identifier_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;if&apos; keyword.
        /// </summary>
        internal static string TokenCode_If_Name {
            get {
                return ResourceManager.GetString("TokenCode_If_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If null &apos;??&apos;.
        /// </summary>
        internal static string TokenCode_IfNull_Name {
            get {
                return ResourceManager.GetString("TokenCode_IfNull_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;implicit&apos; keyword.
        /// </summary>
        internal static string TokenCode_Implicit_Name {
            get {
                return ResourceManager.GetString("TokenCode_Implicit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;in&apos; keyword.
        /// </summary>
        internal static string TokenCode_In_Name {
            get {
                return ResourceManager.GetString("TokenCode_In_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment &apos;++&apos;.
        /// </summary>
        internal static string TokenCode_Increment_Name {
            get {
                return ResourceManager.GetString("TokenCode_Increment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;interface&apos; keyword.
        /// </summary>
        internal static string TokenCode_Interface_Name {
            get {
                return ResourceManager.GetString("TokenCode_Interface_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;internal&apos; keyword.
        /// </summary>
        internal static string TokenCode_Internal_Name {
            get {
                return ResourceManager.GetString("TokenCode_Internal_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;is&apos; keyword.
        /// </summary>
        internal static string TokenCode_Is_Name {
            get {
                return ResourceManager.GetString("TokenCode_Is_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal value.
        /// </summary>
        internal static string TokenCode_Literal_Code {
            get {
                return ResourceManager.GetString("TokenCode_Literal_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal value {0}.
        /// </summary>
        internal static string TokenCode_Literal_Name {
            get {
                return ResourceManager.GetString("TokenCode_Literal_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;lock&apos; keyword.
        /// </summary>
        internal static string TokenCode_Lock_Name {
            get {
                return ResourceManager.GetString("TokenCode_Lock_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical AND &apos;&amp;&amp;&apos;.
        /// </summary>
        internal static string TokenCode_LogicalAnd_Name {
            get {
                return ResourceManager.GetString("TokenCode_LogicalAnd_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical NOT &apos;!&apos;.
        /// </summary>
        internal static string TokenCode_LogicalNot_Name {
            get {
                return ResourceManager.GetString("TokenCode_LogicalNot_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical OR &apos;||&apos;.
        /// </summary>
        internal static string TokenCode_LogicalOR_Name {
            get {
                return ResourceManager.GetString("TokenCode_LogicalOR_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus &apos;-&apos;.
        /// </summary>
        internal static string TokenCode_Minus_Name {
            get {
                return ResourceManager.GetString("TokenCode_Minus_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus &apos;%&apos;.
        /// </summary>
        internal static string TokenCode_Modulus_Name {
            get {
                return ResourceManager.GetString("TokenCode_Modulus_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply &apos;*&apos;.
        /// </summary>
        internal static string TokenCode_Multiply_Name {
            get {
                return ResourceManager.GetString("TokenCode_Multiply_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;namespace&apos; keyword.
        /// </summary>
        internal static string TokenCode_Namespace_Name {
            get {
                return ResourceManager.GetString("TokenCode_Namespace_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;new&apos; keyword.
        /// </summary>
        internal static string TokenCode_New_Name {
            get {
                return ResourceManager.GetString("TokenCode_New_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;operator&apos; keyword.
        /// </summary>
        internal static string TokenCode_Operator_Name {
            get {
                return ResourceManager.GetString("TokenCode_Operator_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;out&apos; keyword.
        /// </summary>
        internal static string TokenCode_Out_Name {
            get {
                return ResourceManager.GetString("TokenCode_Out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;override&apos; keyword.
        /// </summary>
        internal static string TokenCode_Override_Name {
            get {
                return ResourceManager.GetString("TokenCode_Override_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;params&apos; keyword.
        /// </summary>
        internal static string TokenCode_Params_Name {
            get {
                return ResourceManager.GetString("TokenCode_Params_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close parenthesis &apos;)&apos;.
        /// </summary>
        internal static string TokenCode_ParenthesisClose_Name {
            get {
                return ResourceManager.GetString("TokenCode_ParenthesisClose_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open parenthesis &apos;(&apos;.
        /// </summary>
        internal static string TokenCode_ParenthesisOpen_Name {
            get {
                return ResourceManager.GetString("TokenCode_ParenthesisOpen_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus &apos;+&apos;.
        /// </summary>
        internal static string TokenCode_Plus_Name {
            get {
                return ResourceManager.GetString("TokenCode_Plus_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;private&apos; keyword.
        /// </summary>
        internal static string TokenCode_Private_Name {
            get {
                return ResourceManager.GetString("TokenCode_Private_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;protected&apos; keyword.
        /// </summary>
        internal static string TokenCode_Protected_Name {
            get {
                return ResourceManager.GetString("TokenCode_Protected_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;public&apos; keyword.
        /// </summary>
        internal static string TokenCode_Public_Name {
            get {
                return ResourceManager.GetString("TokenCode_Public_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;readonly&apos; keyword.
        /// </summary>
        internal static string TokenCode_Readonly_Name {
            get {
                return ResourceManager.GetString("TokenCode_Readonly_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;ref&apos; keyword.
        /// </summary>
        internal static string TokenCode_Ref_Name {
            get {
                return ResourceManager.GetString("TokenCode_Ref_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;return&apos; keyword.
        /// </summary>
        internal static string TokenCode_Return_Name {
            get {
                return ResourceManager.GetString("TokenCode_Return_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right arrow &apos;-&gt;&apos;.
        /// </summary>
        internal static string TokenCode_RightArrow_Name {
            get {
                return ResourceManager.GetString("TokenCode_RightArrow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;sealed&apos; keyword.
        /// </summary>
        internal static string TokenCode_Sealed_Name {
            get {
                return ResourceManager.GetString("TokenCode_Sealed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolon &apos;;&apos;.
        /// </summary>
        internal static string TokenCode_Semicolon_Name {
            get {
                return ResourceManager.GetString("TokenCode_Semicolon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift left &apos;&lt;&lt;&apos;.
        /// </summary>
        internal static string TokenCode_ShiftLeft_Name {
            get {
                return ResourceManager.GetString("TokenCode_ShiftLeft_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift right &apos;&gt;&gt;&apos;.
        /// </summary>
        internal static string TokenCode_ShiftRight_Name {
            get {
                return ResourceManager.GetString("TokenCode_ShiftRight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;sizeof&apos; keyword.
        /// </summary>
        internal static string TokenCode_Sizeof_Name {
            get {
                return ResourceManager.GetString("TokenCode_Sizeof_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;stackalloc&apos; keyword.
        /// </summary>
        internal static string TokenCode_Stackalloc_Name {
            get {
                return ResourceManager.GetString("TokenCode_Stackalloc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;static&apos; keyword.
        /// </summary>
        internal static string TokenCode_Static_Name {
            get {
                return ResourceManager.GetString("TokenCode_Static_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;struct&apos; keyword.
        /// </summary>
        internal static string TokenCode_Struct_Name {
            get {
                return ResourceManager.GetString("TokenCode_Struct_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;switch&apos; keyword.
        /// </summary>
        internal static string TokenCode_Switch_Name {
            get {
                return ResourceManager.GetString("TokenCode_Switch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;this&apos; keyword.
        /// </summary>
        internal static string TokenCode_This_Name {
            get {
                return ResourceManager.GetString("TokenCode_This_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;throw&apos; keyword.
        /// </summary>
        internal static string TokenCode_Throw_Name {
            get {
                return ResourceManager.GetString("TokenCode_Throw_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinary operator &apos;?&apos;.
        /// </summary>
        internal static string TokenCode_Trinary_Name {
            get {
                return ResourceManager.GetString("TokenCode_Trinary_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;try&apos; keyword.
        /// </summary>
        internal static string TokenCode_Try_Name {
            get {
                return ResourceManager.GetString("TokenCode_Try_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type literal.
        /// </summary>
        internal static string TokenCode_TypeLiteral_Code {
            get {
                return ResourceManager.GetString("TokenCode_TypeLiteral_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Type.
        /// </summary>
        internal static string TokenCode_TypeLiteral_Name {
            get {
                return ResourceManager.GetString("TokenCode_TypeLiteral_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;typeof&apos; keyword.
        /// </summary>
        internal static string TokenCode_Typeof_Name {
            get {
                return ResourceManager.GetString("TokenCode_Typeof_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;unchecked&apos; keyword.
        /// </summary>
        internal static string TokenCode_Unchecked_Name {
            get {
                return ResourceManager.GetString("TokenCode_Unchecked_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;unsafe&apos; keyword.
        /// </summary>
        internal static string TokenCode_Unsafe_Name {
            get {
                return ResourceManager.GetString("TokenCode_Unsafe_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;using&apos; keyword.
        /// </summary>
        internal static string TokenCode_Using_Name {
            get {
                return ResourceManager.GetString("TokenCode_Using_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;virtual&apos; keyword.
        /// </summary>
        internal static string TokenCode_Virtual_Name {
            get {
                return ResourceManager.GetString("TokenCode_Virtual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;volatile&apos; keyword.
        /// </summary>
        internal static string TokenCode_Volatile_Name {
            get {
                return ResourceManager.GetString("TokenCode_Volatile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;while&apos; keyword.
        /// </summary>
        internal static string TokenCode_While_Name {
            get {
                return ResourceManager.GetString("TokenCode_While_Name", resourceCulture);
            }
        }
    }
}
