//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glare.Assets.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glare.Assets.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data; expected {0}, received {1}..
        /// </summary>
        internal static string AssetLoadError_InvalidData {
            get {
                return ResourceManager.GetString("AssetLoadError_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file encountered..
        /// </summary>
        internal static string AssetLoadError_UnexpectedEndOfFile {
            get {
                return ResourceManager.GetString("AssetLoadError_UnexpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected the stream position to be {0}, but it is at {1}..
        /// </summary>
        internal static string AssetLoadError_UnexpectedPosition {
            get {
                return ResourceManager.GetString("AssetLoadError_UnexpectedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This format is used if nothing else can match and the asset does not appear to be text..
        /// </summary>
        internal static string BinaryFormatDescription {
            get {
                return ResourceManager.GetString("BinaryFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Fallback Format.
        /// </summary>
        internal static string BinaryFormatName {
            get {
                return ResourceManager.GetString("BinaryFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DirectDraw Surface (DDS) format is a texture storage format that directly stores textures to disk. This gives it advantages in storing compressed texture formats, but it is otherwise an uncompressed format..
        /// </summary>
        internal static string DdsFormatDescription {
            get {
                return ResourceManager.GetString("DdsFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectDraw Surface (DDS) Format.
        /// </summary>
        internal static string DdsFormatName {
            get {
                return ResourceManager.GetString("DdsFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This contains file formats that come with the default Glare library..
        /// </summary>
        internal static string DefaultPluginDescription {
            get {
                return ResourceManager.GetString("DefaultPluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Glare Plugin.
        /// </summary>
        internal static string DefaultPluginName {
            get {
                return ResourceManager.GetString("DefaultPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DownArrowImage {
            get {
                object obj = ResourceManager.GetObject("DownArrowImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
